services:
  db:
    image: postgres:16
    container_name: edu_postgres

    environment:
      POSTGRES_DB: edu_center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: edu_backend

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data: