# Generated by Django 6.0.4 on 2026-04-27 10:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('subjects', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingtier',
            old_name='subscription_plan',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='status',
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='lessons_per_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='subjects',
            field=models.ManyToManyField(related_name='plans', to='subjects.subject'),
        ),
    ]
