# Generated by Django 6.0.4 on 2026-04-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_subscription_plan_pricingtier_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingtier',
            old_name='plan',
            new_name='subscription_plan',
        ),
    ]
