# Generated by Django 6.0.4 on 2026-04-27 09:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('lessons', '0002_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='students',
        ),
        migrations.RemoveField(
            model_name='lessontemplate',
            name='weekday',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_lessons', to='students.student'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 12, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 9, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_templates', to='students.student'),
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='weekdays',
            field=models.JSONField(default=[0]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_lessons', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_templates', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LessonStudent',
        ),
    ]
