# Generated by Django 6.0.3 on 2026-04-27 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       ('lessons', '0003_remove_lesson_students_remove_lessontemplate_weekday_and_more'),
       ]

    operations = [
        migrations.AddField(
            model_name='lessontemplate',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessontemplate',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessontemplate',
            name='weekdays',
            field=models.JSONField(),
        ),
    ]
