# Generated by Django 6.0.4 on 2026-04-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_lesson_students_remove_lessontemplate_weekday_and_more'),
        ('lessons', '0004_lessontemplate_end_time_lessontemplate_start_time_and_more'),
    ]

    operations = [
    ]
